# Generated by Django 5.2.7 on 2025-10-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
