version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - APP_MODE=dev  # Switches between: dev, prod, worker, scheduler, web
      # --- Supabase Database Credentials ---
      - DB_NAME=postgres
      - DB_USER=postgres.sbxvsblxaqtdahwmpdsk
      - DB_PASSWORD=LeNouveauPassword1@AllAccounts
      - DB_HOST=aws-1-eu-west-1.pooler.supabase.com
      - DB_PORT=6543
      # --- Celery Broker URL (Points to the container's internal Redis) ---
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    restart: always