# Generated by Django 5.2.7 on 2026-02-01 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('def_address', models.CharField(blank=True, max_length=60, null=True)),
                ('def_country', models.CharField(blank=True, max_length=60, null=True)),
                ('def_quarter_town', models.CharField(blank=True, max_length=60, null=True)),
                ('deliv_address', models.CharField(blank=True, max_length=60, null=True)),
                ('deliv_country', models.CharField(blank=True, max_length=60, null=True)),
                ('deliv_quarter_town', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(default='produits/avatar_kbwhgu.png', upload_to='profile_pics/')),
                ('code_revendeur', models.CharField(default='0000', max_length=4)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revendeur', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
