# Generated by Django 5.2.7 on 2026-01-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_def_address_profile_def_quarter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='def_quarter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='def_quarter_ville',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deliv_quarter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deliv_quarter_ville',
        ),
        migrations.AddField(
            model_name='profile',
            name='def_country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='def_quarter_town',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deliv_country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='deliv_quarter_town',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='def_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deliv_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
