# Generated by Django 5.2.7 on 2026-01-11 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_profile_def_quarter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="code_revendeur",
            field=models.CharField(default="0000", max_length=4),
        ),
        migrations.AddField(
            model_name="profile",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revendeur",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
