# Generated by Django 5.2.7 on 2026-02-28 01:14

import django.core.validators
import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="categories/bannerOne_jemfnr.png",
                        upload_to="categories/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("bot_reply", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Chat",
                "verbose_name_plural": "Logs Chat",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_from_cart", models.BooleanField(default=False)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("order", "Commande"), ("chat", "Discussion")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_order_assigned", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attente", "En attente"),
                            ("traitement", "Traitement"),
                            ("terminé", "Terminé"),
                        ],
                        default="attente",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_revendeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_executer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_maker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversation",
            name="related_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="shop.order",
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(
                        max_length=255,
                        validators=[shop.models.validate_description_length],
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_primary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "category_legacy",
                    models.CharField(
                        choices=[
                            ("Smartphone", "Smartphone"),
                            ("Chargeurs", "Chargeurs"),
                            ("Audio", "Audio"),
                            ("Ordinateurs", "Ordinateurs"),
                            ("Montres connectées", "Montres connectées"),
                            ("Tablettes", "Tablettes"),
                            ("Habits/Homme", "Habits → Homme"),
                            ("Habits/Femme", "Habits → Femme"),
                            ("Habits/Enfants", "Habits → Enfants"),
                            ("Habits/Souliers", "Habits → Souliers"),
                        ],
                        default="Smartphone",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
                ("badge", models.CharField(blank=True, max_length=100, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("reviews", models.PositiveIntegerField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_wish", models.DateField(blank=True, null=True)),
                (
                    "price_solde",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "solde_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "image_one",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
                (
                    "image_two",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
                (
                    "image_three",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[shop.models.validate_long_description],
                    ),
                ),
                (
                    "chara_entretien",
                    models.TextField(
                        blank=True,
                        help_text="Séparez les éléments par des sauts de ligne ou des ';'",
                        null=True,
                    ),
                ),
                (
                    "delivery_policy_phase1",
                    models.TextField(
                        blank=True,
                        help_text="Phase 1 de la politique de livraison",
                        null=True,
                    ),
                ),
                (
                    "delivery_policy_phase2",
                    models.TextField(
                        blank=True,
                        help_text="Phase 2 de la politique de livraison",
                        null=True,
                    ),
                ),
                (
                    "category_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonies",
                        to="shop.product",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_achat", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "price_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("OrangeMoney", "Orange Money"),
                            ("AirtelMoney", "Airtel Money"),
                            ("M-Pesa", "M-Pesa"),
                            ("Cash", "Cash"),
                        ],
                        default="Cash",
                        max_length=50,
                    ),
                ),
                ("date_enregistrement", models.DateTimeField(auto_now_add=True)),
                ("vendu_a", models.TextField(blank=True, max_length=50, null=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventes",
                        to="shop.product",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="messages/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("seen", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="shop.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["conversation", "timestamp"],
                        name="shop_messag_convers_d648c2_idx",
                    ),
                    models.Index(
                        fields=["sender"], name="shop_messag_sender__fdec58_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FavoriteProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoris",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favoris",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit Favori",
                "verbose_name_plural": "Produits Favoris",
                "unique_together": {("utilisateur", "produit")},
            },
        ),
    ]
