# Generated by Django 5.2.7 on 2026-05-05 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="vente",
            options={"ordering": ["-date_achat"]},
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="shop_messag_convers_d648c2_idx",
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="shop_messag_sender__fdec58_idx",
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["-created_at"], name="conversation_created_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "-timestamp"], name="message_conv_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-timestamp"], name="message_sender_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["-timestamp"], name="message_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="notification_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["-created_at"], name="notification_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notification_user_read_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="order_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["assigned_revendeur", "-created_at"],
                name="order_revendeur_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="order_status_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["-created_at"], name="order_recent_idx"),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["utilisateur", "-date_achat"], name="vente_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["produit", "-date_achat"], name="vente_product_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(fields=["-date_achat"], name="vente_date_idx"),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["utilisateur", "date_achat"], name="vente_user_sales_idx"
            ),
        ),
    ]
