# Generated by Django 5.2.7 on 2026-05-05 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_add_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The question asked by user"),
                ),
                (
                    "response_text",
                    models.TextField(blank=True, help_text="AI assistant response"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "French"),
                            ("en", "English"),
                            ("sw", "Swahili"),
                        ],
                        default="fr",
                        max_length=5,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                            ("frustrated", "Frustrated"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Extracted keywords from question"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"], name="pq_product_date_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="pq_user_date_idx"
                    ),
                    models.Index(fields=["-created_at"], name="pq_recent_idx"),
                    models.Index(fields=["sentiment"], name="pq_sentiment_idx"),
                ],
            },
        ),
    ]
