# Generated by Django 5.2.7 on 2025-10-07 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_feature_alter_panieritem_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date_wish',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_primary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Chargeurs', 'Chargeurs'), ('Audio', 'Audio'), ('Ordinateurs', 'Ordinateurs'), ('Montres connectées', 'Montres connectées'), ('Tablettes', 'Tablettes'), ('Habits/Homme', 'Habits → Homme'), ('Habits/Femme', 'Habits → Femme'), ('Habits/Enfants', 'Habits → Enfants'), ('Habits/Souliers', 'Habits → Souliers')], default='Smartphone', max_length=100),
        ),
    ]
