# Generated by Django 5.2.7 on 2025-10-10 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_date_added_product_date_wish_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_legacy',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Chargeurs', 'Chargeurs'), ('Audio', 'Audio'), ('Ordinateurs', 'Ordinateurs'), ('Montres connectées', 'Montres connectées'), ('Tablettes', 'Tablettes'), ('Habits/Homme', 'Habits → Homme'), ('Habits/Femme', 'Habits → Femme'), ('Habits/Enfants', 'Habits → Enfants'), ('Habits/Souliers', 'Habits → Souliers')], default='Smartphone', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('price_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
