# Generated by Django 5.2.7 on 2025-10-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='method',
            field=models.CharField(choices=[('OrangeMMoney', 'Orange Money'), ('AirtelMoney', 'Airtel Money'), ('M-Pesa', 'M-Pesa'), ('Cash', 'Cash')], default='Cash', max_length=50),
        ),
    ]
