# Generated by Django 5.2.7 on 2025-10-10 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_vente_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
