# Generated by Django 5.2.7 on 2025-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_vente_date_enregistrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='method',
            field=models.CharField(choices=[('OrangeMoney', 'Orange Money'), ('AirtelMoney', 'Airtel Money'), ('M-Pesa', 'M-Pesa'), ('Cash', 'Cash')], default='Cash', max_length=50),
        ),
    ]
