# Generated by Django 5.2.7 on 2025-11-19 13:35

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_price_solde_product_solde_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chara_entretien',
            field=models.TextField(blank=True, help_text="Séparez les éléments par des sauts de ligne ou des ';'", null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_policy_phase1',
            field=models.TextField(blank=True, help_text='Phase 1 de la politique de livraison', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_policy_phase2',
            field=models.TextField(blank=True, help_text='Phase 2 de la politique de livraison', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True, validators=[shop.models.validate_long_description]),
        ),
    ]
