# Generated by Django 5.2.7 on 2025-11-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_favoriteproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='shop.product'),
        ),
    ]
