# Generated by Django 5.2.7 on 2025-11-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_vente_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panieritem',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='panieritem',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.DeleteModel(
            name='PanierItem',
        ),
    ]
