# Generated by Django 5.2.7 on 2025-11-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_message_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Commande'), ('chat', 'Discussion')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.conversation'),
        ),
    ]
