# Generated by Django 5.2.7 on 2025-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_notification_type_alter_notification_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_order_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
