# Generated by Django 5.2.7 on 2025-11-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_notification_is_order_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='vendu_a',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
