# Generated by Django 5.2.7 on 2025-11-30 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_vente_vendu_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_wait', models.DurationField(default=datetime.timedelta(days=45))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
