# Generated by Django 5.2.7 on 2025-11-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_assistant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assistant',
        ),
    ]
