# Generated by Django 5.2.7 on 2026-01-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_order_assigned_revendeur_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/cat_default.png', upload_to='categories/'),
        ),
    ]
