# Generated by Django 5.2.7 on 2026-01-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/bannerOne_jemfnr.png', upload_to='categories/'),
        ),
    ]
