# shop/view_components/assistant/tasks.py
"""
Celery tasks for AI assistant background work.

The primary chat reply is now generated by a synchronous streaming view
(general.chat_stream) - it is NOT a Celery task, since streaming tokens back
to an open HTTP connection is inherently a request-scoped, user-visible
operation Celery isn't suited for (see shop/services/gemini_stream.py).

These tasks handle everything that CAN be deferred, dispatched by
chat_stream once the reply has finished streaming:
- post_stream_followup_task: classify the reply (language/sentiment/
  complaint) and dispatch a support email if needed, plus analytics tracking
- save_chat_log_task: persist the conversation
- send_support_email_task: generate + send the complaint notification email
"""

import logging
from celery import shared_task
from asgiref.sync import async_to_sync

logger = logging.getLogger(__name__)


# ── Post-stream follow-up task ─────────────────────────────────────────────────
@shared_task(
    name="shop.assistant.tasks.post_stream_followup",
    ignore_result=True,
    max_retries=1,
    default_retry_delay=3,
    time_limit=30,
)
def post_stream_followup_task(
    user_id: int | None,
    message: str,
    reply: str,
    matched_product_id: int | None,
) -> None:
    """
    Runs after a reply has already been streamed to the user. Classifies the
    exchange (language/sentiment/complaint), records it for analytics, and
    dispatches a support email if it was a complaint.
    """
    try:
        from shop.services.assistant_service import classify_reply
        from shop.models import ProductQuestion

        intent_data = async_to_sync(classify_reply)(message=message, reply=reply)

        ProductQuestion.objects.create(
            user_id=user_id,
            product_id=matched_product_id,
            question_text=message,
            response_text=reply,
            language=intent_data.get("language", "fr"),
            sentiment=intent_data.get("sentiment", "neutral"),
        )

        complaint_type = intent_data.get("complaint_type")
        if intent_data.get("is_complaint") and complaint_type not in (None, "", "aucun"):
            send_support_email_task.delay(
                complaint_type=complaint_type,
                complaint_summary=intent_data.get("complaint_summary", ""),
                client_message=message,
                user_id=user_id,
            )
            logger.debug("[FollowupTask] Support email queued")

    except Exception as e:
        logger.warning(f"[FollowupTask] Failed: {e}", exc_info=True)


# ── Support email dispatch task ────────────────────────────────────────────────
@shared_task(
    name="shop.assistant.tasks.send_support_email",
    ignore_result=True,
    max_retries=2,
    default_retry_delay=5,
    time_limit=30,
)
def send_support_email_task(
    complaint_type: str,
    complaint_summary: str,
    client_message: str,
    user_id: int | None,
) -> None:
    """Generate and send a support notification email for a detected complaint."""
    logger.info(f"[SupportTask] started: type={complaint_type}, user={user_id}")

    try:
        from shop.view_components.assistant.support import (
            _get_mukubwa_emails,
            _send_email,
        )
        from shop.services.assistant_service import generate_support_email_async

        mukubwa_emails = _get_mukubwa_emails()
        if not mukubwa_emails:
            logger.warning("[SupportTask] No recipients in mukubwa group")
            return

        email_data = async_to_sync(generate_support_email_async)(
            complaint_type=complaint_type,
            client_message=client_message,
            complaint_summary=complaint_summary,
            user_id=user_id,
        )

        if not email_data:
            logger.warning("[SupportTask] Email generation failed")
            return

        user = None
        if user_id:
            from django.contrib.auth import get_user_model

            User = get_user_model()
            user = User.objects.filter(pk=user_id).first()

        success = _send_email(email_data, mukubwa_emails, user)

        if success:
            logger.info(f"[SupportTask] Email sent to {len(mukubwa_emails)} recipients")
        else:
            logger.error("[SupportTask] Email send failed")

    except Exception as e:
        logger.error(f"[SupportTask] Failed: {e}", exc_info=True)
        # Don't retry - this isn't critical path


# ── Chat log persistence task ─────────────────────────────────────────────────
@shared_task(
    name="shop.assistant.tasks.save_chat_log",
    ignore_result=True,
    max_retries=1,
    default_retry_delay=3,
    time_limit=15,
)
def save_chat_log_task(
    user_id: int | None,
    user_message: str,
    bot_reply: str,
) -> None:
    """Save chat conversation to database (non-blocking, fire-and-forget)."""
    try:
        from shop.models import ChatLog
        from django.contrib.auth import get_user_model

        User = get_user_model()
        user = None

        if user_id:
            try:
                user = User.objects.get(pk=user_id)
            except User.DoesNotExist:
                logger.warning(f"[LogTask] User {user_id} not found")

        ChatLog.objects.create(
            user=user,
            user_message=user_message[:500],
            bot_reply=bot_reply[:1000],
        )

        logger.debug(f"[LogTask] Chat log saved for user {user_id}")

    except Exception as e:
        logger.warning(f"[LogTask] Failed to save chat log: {e}")
